[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_allowance_wallet = "9qQcnqLMemRQZJTFBkgULoAK6AwGVPdDcS9chXZmDTpM"

[programs.devnet]
smart_allowance_wallet = "9qQcnqLMemRQZJTFBkgULoAK6AwGVPdDcS9chXZmDTpM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
